In [6]:
# import dependencies
import pandas as pd
import sqlalchemy 
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect
# read in Christmas Carols csv
df = pd.read_csv('ChristmasCarols.csv')
carol_df = pd.DataFrame(df)
carol_df.head()

,Title,Artist,Year,Additional information
0,"""Christmas Eve/Sarajevo 12/24""",Savatage,1996,"The song is a medley including ""God Rest Ye Me..."
1,"""Redneck 12 Days of Christmas""",Jeff Foxworthy,1995,Peaked at No. 18 on Billboard's Hot Country Si...
2,"""Christmas Is""",Jim Brickman featuring Mark Masri,2008,Peaked at No. 18 on the Billboard Hot Adult Co...
3,"""Christmas Time""",John Anderson,1994,Reached No. 57 on the Billboard Hot Country Si...
4,"""Christmas Time Is Here""","Ray Parker, Jr.",1982,Re-issued in 1984 as the B-side of Parker's to...

In [7]:
# clean data
# clean Title column
carol_df['Title'].str.replace(r"\"","")

<ipython-input-7-edfeb3a3c376>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  carol_df['Title'].str.replace(r"\"","")

0               Christmas Eve/Sarajevo 12/24
1               Redneck 12 Days of Christmas
2                               Christmas Is
3                             Christmas Time
4                     Christmas Time Is Here
                       ...
608    Yes, Patricia, There Is a Santa Claus
609                             Yingle Bells
610            You're a Mean One, Mr. Grinch
611            You're a Mean One, Mr. Grinch
612                   'Zat You, Santa Claus?
Name: Title, Length: 613, dtype: object

In [8]:
carol_df.head()

,Title,Artist,Year,Additional information
0,"""Christmas Eve/Sarajevo 12/24""",Savatage,1996,"The song is a medley including ""God Rest Ye Me..."
1,"""Redneck 12 Days of Christmas""",Jeff Foxworthy,1995,Peaked at No. 18 on Billboard's Hot Country Si...
2,"""Christmas Is""",Jim Brickman featuring Mark Masri,2008,Peaked at No. 18 on the Billboard Hot Adult Co...
3,"""Christmas Time""",John Anderson,1994,Reached No. 57 on the Billboard Hot Country Si...
4,"""Christmas Time Is Here""","Ray Parker, Jr.",1982,Re-issued in 1984 as the B-side of Parker's to...

In [9]:
# clean title column in dataframe
carol_df["Title"] =carol_df['Title'].str.replace(r"\"","")

<ipython-input-9-892128170bb3>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  carol_df["Title"] =carol_df['Title'].str.replace(r"\"","")

In [10]:
carol_df.head(10)

,Title,Artist,Year,Additional information
0,Christmas Eve/Sarajevo 12/24,Savatage,1996,"The song is a medley including ""God Rest Ye Me..."
1,Redneck 12 Days of Christmas,Jeff Foxworthy,1995,Peaked at No. 18 on Billboard's Hot Country Si...
2,Christmas Is,Jim Brickman featuring Mark Masri,2008,Peaked at No. 18 on the Billboard Hot Adult Co...
3,Christmas Time,John Anderson,1994,Reached No. 57 on the Billboard Hot Country Si...
4,Christmas Time Is Here,"Ray Parker, Jr.",1982,Re-issued in 1984 as the B-side of Parker's to...
5,Christmastime,The Smashing Pumpkins,1997,An original song written by Billy Corgan and r...
6,Happy New Year,ABBA,1980,Released as a CD single in 1999.
7,Mistletoe,Justin Bieber,2011,Peaked at No. 11 on the Billboard Hot 100 sing...
8,The Night Before Christmas,Carly Simon,1992,Written and recorded by Simon for the 1992 fil...
9,This Christmas,Matthew and Gunnar Nelson featuring Alyssa Bon...,2015,Peaked at No. 17 on the Billboard Adult Contem...

In [11]:
# clean Artist column
carol_df["Artist"] =carol_df['Artist'].str.replace(r"\"","")

<ipython-input-11-4fa7528108a3>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  carol_df["Artist"] =carol_df['Artist'].str.replace(r"\"","")

In [12]:
carol_df.head(10)

,Title,Artist,Year,Additional information
0,Christmas Eve/Sarajevo 12/24,Savatage,1996,"The song is a medley including ""God Rest Ye Me..."
1,Redneck 12 Days of Christmas,Jeff Foxworthy,1995,Peaked at No. 18 on Billboard's Hot Country Si...
2,Christmas Is,Jim Brickman featuring Mark Masri,2008,Peaked at No. 18 on the Billboard Hot Adult Co...
3,Christmas Time,John Anderson,1994,Reached No. 57 on the Billboard Hot Country Si...
4,Christmas Time Is Here,"Ray Parker, Jr.",1982,Re-issued in 1984 as the B-side of Parker's to...
5,Christmastime,The Smashing Pumpkins,1997,An original song written by Billy Corgan and r...
6,Happy New Year,ABBA,1980,Released as a CD single in 1999.
7,Mistletoe,Justin Bieber,2011,Peaked at No. 11 on the Billboard Hot 100 sing...
8,The Night Before Christmas,Carly Simon,1992,Written and recorded by Simon for the 1992 fil...
9,This Christmas,Matthew and Gunnar Nelson featuring Alyssa Bon...,2015,Peaked at No. 17 on the Billboard Adult Contem...

In [13]:
# drop unwanted columns
carol_df = carol_df.drop(columns=['Additional information', 'Year'])
carol_df.head()

                          Title                             Artist
0  Christmas Eve/Sarajevo 12/24                           Savatage
1  Redneck 12 Days of Christmas                     Jeff Foxworthy
2                  Christmas Is  Jim Brickman featuring Mark Masri
3                Christmas Time                      John Anderson
4        Christmas Time Is Here                    Ray Parker, Jr.

In [26]:
# rename columns
carol_df = carol_df.rename(columns={'Title': 'Song', 'Artist': 'Performer'})
carol_df.head()

                           Song                          Performer
0  Christmas Eve/Sarajevo 12/24                           Savatage
1  Redneck 12 Days of Christmas                     Jeff Foxworthy
2                  Christmas Is  Jim Brickman featuring Mark Masri
3                Christmas Time                      John Anderson
4        Christmas Time Is Here                    Ray Parker, Jr.

In [14]:
# read in Top 100 Billboard csv
Top100_df = pd.read_csv('Top_100.csv')

In [15]:
Top100_df.head()

,url,WeekID,Week Position,Song,Performer,SongID,Instance,Previous Week Position,Peak Position,Weeks on Chart
0,http://www.billboard.com/charts/hot-100/1965-0...,7/17/1965,34,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,45.0,34,4
1,http://www.billboard.com/charts/hot-100/1965-0...,7/24/1965,22,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,34.0,22,5
2,http://www.billboard.com/charts/hot-100/1965-0...,7/31/1965,14,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,22.0,14,6
3,http://www.billboard.com/charts/hot-100/1965-0...,8/7/1965,10,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,14.0,10,7
4,http://www.billboard.com/charts/hot-100/1965-0...,8/14/1965,8,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,10.0,8,8

In [16]:
#drop unwanted columns
Top100_df.drop(columns= ['url'])

,WeekID,Week Position,Song,Performer,SongID,Instance,Previous Week Position,Peak Position,Weeks on Chart
0,7/17/1965,34,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,45.0,34,4
1,7/24/1965,22,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,34.0,22,5
2,7/31/1965,14,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,22.0,14,6
3,8/7/1965,10,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,14.0,10,7
4,8/14/1965,8,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,10.0,8,8
...,...,...,...,...,...,...,...,...,...
327890,10/20/2018,22,God Is A Woman,Ariana Grande,God Is A WomanAriana Grande,1,21.0,8,13
327891,5/21/1977,22,I Wanna Get Next To You,Rose Royce,I Wanna Get Next To YouRose Royce,1,10.0,10,13
327892,5/23/1981,22,I Can't Stand It,Eric Clapton And His Band,I Can't Stand ItEric Clapton And His Band,1,12.0,10,13
327893,9/29/1973,22,Here I Am Come & Take Me,Al Green,Here I Am Come & Take MeAl Green,1,16.0,10,13
327894,11/28/2020,22,Hawai,Maluma & The Weeknd,HawaiMaluma & The Weeknd,1,12.0,12,13

In [17]:
# rename columns
Top100_df = Top100_df.rename(columns={'Week Position': 'week_position', 
                            'Previous Week Position': 'previous_week_position',
                          'Peak Position': 'peak_position',
                          'Weeks on Chart': 'weeks_on_chart'})
Top100_df.head()

,url,WeekID,week_position,Song,Performer,SongID,Instance,previous_week_position,peak_position,weeks_on_chart
0,http://www.billboard.com/charts/hot-100/1965-0...,7/17/1965,34,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,45.0,34,4
1,http://www.billboard.com/charts/hot-100/1965-0...,7/24/1965,22,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,34.0,22,5
2,http://www.billboard.com/charts/hot-100/1965-0...,7/31/1965,14,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,22.0,14,6
3,http://www.billboard.com/charts/hot-100/1965-0...,8/7/1965,10,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,14.0,10,7
4,http://www.billboard.com/charts/hot-100/1965-0...,8/14/1965,8,Don't Just Stand There,Patty Duke,Don't Just Stand TherePatty Duke,1,10.0,8,8

In [18]:
# merge table of top_100 and carol merged on song and artist
merged_xmas = pd.read_csv('christmas_billboard_data.csv')
merged_xmas = merged_xmas.drop(columns = 'url')
merged_xmas

,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,month,day
0,12/13/1958,83,RUN RUDOLPH RUN,Chuck Berry,Run Rudolph RunChuck Berry,1,NaN,69,3,1958,12,13
1,12/20/1958,57,JINGLE BELL ROCK,Bobby Helms,Jingle Bell RockBobby Helms,1,NaN,29,19,1958,12,20
2,12/20/1958,73,RUN RUDOLPH RUN,Chuck Berry,Run Rudolph RunChuck Berry,1,83.0,69,3,1958,12,20
3,12/20/1958,86,WHITE CHRISTMAS,Bing Crosby,White ChristmasBing Crosby,1,NaN,12,13,1958,12,20
4,12/27/1958,44,GREEN CHRI$TMA$,Stan Freberg,Green Chri$tma$Stan Freberg,1,NaN,44,2,1958,12,27
...,...,...,...,...,...,...,...,...,...,...,...,...
382,1/7/2017,16,ALL I WANT FOR CHRISTMAS IS YOU,Mariah Carey,All I Want For Christmas Is YouMariah Carey,6,20.0,11,19,2017,1,7
383,1/7/2017,27,ROCKIN' AROUND THE CHRISTMAS TREE,Brenda Lee,Rockin' Around The Christmas TreeBrenda Lee,6,48.0,14,18,2017,1,7
384,1/7/2017,48,IT'S THE MOST WONDERFUL TIME OF THE YEAR,Andy Williams,It's The Most Wonderful Time Of The YearAndy W...,1,NaN,48,1,2017,1,7
385,1/14/2017,35,ALL I WANT FOR CHRISTMAS IS YOU,Mariah Carey,All I Want For Christmas Is YouMariah Carey,6,16.0,11,19,2017,1,14
386,1/14/2017,41,LAST CHRISTMAS,Wham!,Last ChristmasWham!,1,50.0,41,2,2017,1,14

In [20]:
# establish connection to database
# engine = create_engine(f"postgresql://{username}:{password}@localhost:5432/Top_Songs")
engine = create_engine(f"postgresql://postgres:postgres@localhost:5432/Top_Songs")
connection = engine.connect()

In [24]:
# create carol table in PostGres and upload data
import csv
from io import StringIO
def psql_insert_copy(table, conn, keys, data_iter):
    # gets a DBAPI connection that can provide a cursor
    dbapi_conn = conn.connection
    with dbapi_conn.cursor() as cur:
        s_buf = StringIO()
        writer = csv.writer(s_buf)
        writer.writerows(data_iter)
        s_buf.seek(0)

        columns = ', '.join('"{}"'.format(k) for k in keys)
        if table.schema:
            table_name = '{}.{}'.format(table.schema, table.name)
        else:
            table_name = table.name

        sql = 'COPY {} ({}) FROM STDIN WITH CSV'.format(
            table_name, columns)
        cur.copy_expert(sql=sql, file=s_buf)

carol_df.to_sql('carols', engine, method=psql_insert_copy)

In [25]:
# create top 100 table in PostGres and upload data
Top100_df.to_sql('top_100', engine, method=psql_insert_copy)

In [23]:
merged_xmas.to_sql('merged_xmas', engine, method=psql_insert_copy)